### ISSUE TITLE
Controlling randomness in parallel environments

### ISSUE THREAD

**Issue by abadithela** [haosulab/ManiSkill#1000]
Hi, 

I'm trying to control the randomness across parallel environments for a simple pick and place task. I've checked the following [documentation](https://maniskill.readthedocs.io/en/latest/user_guide/concepts/rng.html) and I am setting the same seed when calling env.reset(seed= [x1, x1, ..., x1]) for some seed x1. I did not set any other parameters. I still observe a randomness in the outcome; is there any other seed I should be fixing. Based on the documentation, I thought that passing the same seed during reset will control for the randomness across parallel environments. 

Is there anything else I should be fixing?

Thanks,
Apurva

**Comment by StoneT2000** [comment]
What is your task randomization implementation like?

We recommend
1. `_batched_episode_rng` for any non env state related randomizations (use only in def _load_scene), such as colors of objects, object meshes etc.
2. torch RNG for env state related randomizations (object poses, velocities, qpos, qvels, any other info) (it is already seeded at an episode level using the first number provided, in this case, `x1`: ). Torch RNG is dependent on batch size and the episode level seed (`x1`). This is faster RNG and recommended as a result since env state related randomizations occur most frequently (during def _initialize_episode)

You should be getting the same env state (object pose, velocities) if you keep calling env.reset(seed=[x1, x1, ..., x1]) as long as you only use torch rng for randomizations in def _initialize_episode and use same number of parallel envs

**Comment by abadithela** [comment]
Our initialize_episode function looks like the following:

```
def _initialize_episode(self, env_idx: torch.Tensor, options: dict):
        # use the torch.device context manager to automatically create tensors on CPU or CUDA depending on self.device, the device the environment runs on
        super()._initialize_episode(env_idx, options)
        with torch.device(self.device):
            if self.do_motion_planning:
                self.manip_obj_pcds = []
                self.goal_obj_pcds = []
                if len(self.manip_obj_meshes_raw) > 1:
                    for i in range(len(self.manip_obj_meshes_raw)):
                        manip_mesh = self.manip_obj_meshes_raw[i].copy()
                        goal_mesh = self.goal_obj_meshes_raw[i].copy()
                        manip_pose = self.manip_obj.pose[i]
                        goal_pose = self.goal_obj.pose[i]

                        manip_mesh.apply_transform(
                            manip_pose.sp.to_transformation_matrix()
                        )
                        goal_mesh.apply_transform(
                            goal_pose.sp.to_transformation_matrix()
                        )

                        samples = trimesh.sample.sample_surface_even(
                            manip_mesh, NUM_SAMPLES
                        )
                        pcd = PointCloud(
                            xyz_pts=samples[0].__array__().copy(),
                            normals=manip_mesh.face_normals[samples[1]].copy(),
                        )
                        self.manip_obj_pcds.append(pcd)

                        # visualize_trimesh(manip_mesh, extra_pts=(samples[0].__array__().copy(), manip_mesh.face_normals[samples[1]].copy()))

                        samples = trimesh.sample.sample_surface_even(
                            goal_mesh, NUM_SAMPLES
                        )
                        pcd = PointCloud(
                            xyz_pts=samples[0].__array__().copy(),
                            normals=goal_mesh.face_normals[samples[1]].copy(),
                        )
                        self.goal_obj_pcds.append(pcd)
                else:
                    manip_mesh = self.manip_obj_meshes_raw.copy()
                    goal_mesh = self.goal_obj_meshes_raw.copy()
                    manip_pose = self.manip_obj.pose
                    goal_pose = self.goal_obj.pose

                    manip_mesh.apply_transform(manip_pose.sp.to_transformation_matrix())
                    goal_mesh.apply_transform(goal_pose.sp.to_transformation_matrix())

                    samples = trimesh.sample.sample_surface_even(
                        manip_mesh, NUM_SAMPLES
                    )
                    pcd = PointCloud(
                        xyz_pts=samples[0].__array__().copy(),
                        normals=manip_mesh.face_normals[samples[1]].copy(),
                    )
                    self.manip_obj_pcds.append(pcd)

                    samples = trimesh.sample.sample_surface_even(goal_mesh, NUM_SAMPLES)
                    pcd = PointCloud(
                        xyz_pts=samples[0].__array__().copy(),
                        normals=goal_mesh.face_normals[samples[1]].copy(),
                    )
                    self.goal_obj_pcds.append(pcd)

        print("Initialized episode.")
```
I do have a slightly different initial object poses and states across 8 parallel environments

```
object:
  manip_obj:
  - - -0.18010425567626953
    - -0.05451345443725586
    - -0.0014724209904670715
    - -0.01664203777909279
    - -0.014894228428602219
    - 0.6810619235038757
    - 0.7318850755691528
  - - -0.18010462820529938
    - -0.05451345443725586
    - -0.0014724209904670715
    - -0.016643928363919258
    - -0.014895827509462833
    - 0.6810618042945862
    - 0.7318853139877319
  - - -0.18010425567626953
    - -0.05451345443725586
    - -0.0014724209904670715
    - -0.01664203777909279
    - -0.014894228428602219
    - 0.6810619235038757
    - 0.7318850755691528
  - - -0.18010425567626953
    - -0.0545133538544178
    - -0.0014724228531122208
    - -0.016644518822431564
    - -0.014896633103489876
    - 0.6810618042945862
    - 0.7318852543830872
  - - -0.18010464310646057
    - -0.054513413459062576
    - -0.0014724191278219223
    - -0.016642717644572258
    - -0.01489479560405016
    - 0.6810618042945862
    - 0.7318853139877319
  - - -0.18010425567626953
    - -0.0545133538544178
    - -0.0014724228531122208
    - -0.016644518822431564
    - -0.014896633103489876
    - 0.6810618042945862
    - 0.7318852543830872
  - - -0.18010425567626953
    - -0.05451345443725586
    - -0.0014724209904670715
    - -0.01664203777909279
    - -0.014894228428602219
    - 0.6810619235038757
    - 0.7318850755691528
  - - -0.18010462820529938
    - -0.05451345443725586
    - -0.0014724209904670715
    - -0.016643928363919258
    - -0.014895827509462833
    - 0.6810618042945862
    - 0.7318853139877319
  goal_obj:
  - - -0.40003013610839844
    - 0.19985055923461914
    - 0.010347513481974602
    - 0.6386458873748779
    - 0.646270215511322
    - 0.2927051782608032
    - 0.29797619581222534
  - - -0.4000299572944641
    - 0.19985055923461914
    - 0.010347503237426281
    - 0.6386455297470093
    - 0.6462702751159668
    - 0.2927055060863495
    - 0.29797661304473877
  - - -0.40003013610839844
    - 0.19985055923461914
    - 0.010347513481974602
    - 0.6386458873748779
    - 0.646270215511322
    - 0.2927051782608032
    - 0.29797619581222534
  - - -0.40003013610839844
    - 0.19985029101371765
    - 0.010347497649490833
    - 0.6386450529098511
    - 0.6462699174880981
    - 0.29270657896995544
    - 0.297977477312088
  - - -0.40003010630607605
    - 0.19985036551952362
    - 0.010347498580813408
    - 0.638646125793457
    - 0.6462703347206116
    - 0.2927044928073883
    - 0.29797598719596863
  - - -0.40003013610839844
    - 0.19985029101371765
    - 0.010347497649490833
    - 0.6386450529098511
    - 0.6462699174880981
    - 0.29270657896995544
    - 0.297977477312088
  - - -0.40003013610839844
    - 0.19985055923461914
    - 0.010347513481974602
    - 0.6386458873748779
    - 0.646270215511322
    - 0.2927051782608032
    - 0.29797619581222534
  - - -0.4000299572944641
    - 0.19985055923461914
    - 0.010347503237426281
    - 0.6386455297470093
    - 0.6462702751159668
    - 0.2927055060863495
    - 0.29797661304473877
robot:
  qpos:
  - - 0.0006311589386314154
    - -0.607283353805542
    - 0.0008765700622461736
    - -2.4609134197235107
    - -0.0013599605299532413
    - 1.709039568901062
    - -2.737718023126945e-05
    - 0.03997756168246269
    - 0.03997756168246269
  - - 0.0006351520423777401
    - -0.6072832942008972
    - 0.0008782771183177829
    - -2.460913896560669
    - -0.001358536770567298
    - 1.7090398073196411
    - -3.051835301448591e-05
    - 0.03997756168246269
    - 0.039977557957172394
  - - 0.0006311589386314154
    - -0.607283353805542
    - 0.0008765700622461736
    - -2.4609134197235107
    - -0.0013599605299532413
    - 1.709039568901062
    - -2.737718023126945e-05
    - 0.03997756168246269
    - 0.03997756168246269
  - - 0.0006217869813553989
    - -0.6072818636894226
    - 0.0008718890603631735
    - -2.4609153270721436
    - -0.0013625874416902661
    - 1.7090389728546143
    - -2.0983041395084e-05
    - 0.0399775505065918
    - 0.039977554231882095
  - - 0.0006229110294952989
    - -0.6072821021080017
    - 0.000872477947268635
    - -2.4609153270721436
    - -0.0013623313279822469
    - 1.7090390920639038
    - -2.1774838387500495e-05
    - 0.03997756168246269
    - 0.03997756540775299
  - - 0.0006217869813553989
    - -0.6072818636894226
    - 0.0008718890603631735
    - -2.4609153270721436
    - -0.0013625874416902661
    - 1.7090389728546143
    - -2.0983041395084e-05
    - 0.0399775505065918
    - 0.039977554231882095
  - - 0.0006311589386314154
    - -0.607283353805542
    - 0.0008765700622461736
    - -2.4609134197235107
    - -0.0013599605299532413
    - 1.709039568901062
    - -2.737718023126945e-05
    - 0.03997756168246269
    - 0.03997756168246269
  - - 0.0006351520423777401
    - -0.6072832942008972
    - 0.0008782771183177829
    - -2.460913896560669
    - -0.001358536770567298
    - 1.7090398073196411
    - -3.051835301448591e-05
    - 0.03997756168246269
    - 0.039977557957172394
    
```
